### ISSUE TITLE
Failing to get browser capabilities

### ISSUE THREAD

**Issue by sibbl** [xebia/VisualReview-protractor#17]
When trying to use the project on Windows 10 x84, using Chrome and newest ChromeDriver v2.11 I get the following:

```
Message:
  Failed: Cannot read property 'platform' of undefined
Stack:
  TypeError: Cannot read property 'platform' of undefined
      at _propertiesFn (c:\my\project\src\main\node_modules\visualreview-protractor\visualreview-protractor.js:36:31)
      at Promise.invokeCallback_ (c:\my\project\src\main\node_modules\selenium-webdriver\lib\promise.js:1329:14)
      at TaskQueue.execute_ (c:\my\project\src\main\node_modules\selenium-webdriver\lib\promise.js:2790:14)
      at TaskQueue.executeNext_ (c:\my\project\src\main\node_modules\selenium-webdriver\lib\promise.js:2773:21)
      at asyncRun (c:\my\project\src\main\node_modules\selenium-webdriver\lib\promise.js:2652:27)
      at c:\my\project\src\main\node_modules\selenium-webdriver\lib\promise.js:639:7
      at process._tickCallback (internal/process/next_tick.js:103:7)
  From: Task: <anonymous>
      at Object.takeScreenshot (c:\my\project\src\main\node_modules\visualreview-protractor\visualreview-protractor.js:81:39)
      at Object.<anonymous> (c:\my\project\src\main\websrc\test\e2e\screenShot.spec.js:5:8)
      at c:\my\project\src\main\node_modules\jasminewd2\index.js:96:23
      at new Promise (c:\my\project\src\main\node_modules\selenium-webdriver\lib\promise.js:1043:7)
      at controlFlowExecute (c:\my\project\src\main\node_modules\jasminewd2\index.js:82:18)
      at TaskQueue.execute_ (c:\my\project\src\main\node_modules\selenium-webdriver\lib\promise.js:2790:14)
      at TaskQueue.executeNext_ (c:\my\project\src\main\node_modules\selenium-webdriver\lib\promise.js:2773:21)
      at asyncRun (c:\my\project\src\main\node_modules\selenium-webdriver\lib\promise.js:2697:25)
      at c:\my\project\src\main\node_modules\selenium-webdriver\lib\promise.js:639:7
      at process._tickCallback (internal/process/next_tick.js:103:7)
  From: Task: Run fit("should look beautiful") in control flow
      at Object.<anonymous> (c:\my\project\src\main\node_modules\jasminewd2\index.js:81:14)
      at c:\my\project\src\main\node_modules\jasminewd2\index.js:18:5
      at Promise.invokeCallback_ (c:\my\project\src\main\node_modules\selenium-webdriver\lib\promise.js:1329:14)
      at TaskQueue.execute_ (c:\my\project\src\main\node_modules\selenium-webdriver\lib\promise.js:2790:14)
      at TaskQueue.executeNext_ (c:\my\project\src\main\node_modules\selenium-webdriver\lib\promise.js:2773:21)
      at asyncRun (c:\my\project\src\main\node_modules\selenium-webdriver\lib\promise.js:2652:27)
  From asynchronous test:
  Error
      at Suite.<anonymous> (c:\my\project\src\main\websrc\test\e2e\screenShot.spec.js:3:3)
      at Object.<anonymous> (c:\my\project\src\main\websrc\test\e2e\screenShot.spec.js:2:1)
      at Module._compile (module.js:541:32)
      at Object.Module._extensions..js (module.js:550:10)
      at Module.load (module.js:458:32)
      at tryModuleLoad (module.js:417:12)
```

My capabilities object in my protractor.conf.js looks like this:
    capabilities: {
      browserName: 'chrome',
      chromeOptions: {
        args: [
          '--disable-extensions',
          '--disable-web-security', //disable CORS
        ],
        mobileEmulation: {
          deviceMetrics: {
            width: 1920,
            height: 1080,
            pixelRatio: 1
          }
        }
      },
    },

Any ideas what could help? It also fails to get the browserName etc in the lines below the call which fails.

**Comment by wlsf82** [comment]
Hey @sibbl, take a look at the post I wrote on Medium about this error:
https://medium.com/@walmyrlimaesilv/cannot-read-property-platform-of-undefined-8848acc8bb3#.hl2ro4v8a
I hope it helps you.

**Comment by sibbl** [comment]
Thanks, that helped a lot! I read about the `propertiesFn` in the readme, but never thought that this might not work out of the box. I think it should.

**Comment by wlsf82** [comment]
I'm glad to help you!

**Comment by skwakman** [comment]
@sibbl I agree this this should just work out of the box. It was actually fixed on master a while ago (see PR #14). As some other features were being worked on in the mean time, I haven't created a release of that just yet. Perhaps it's time to do so.

**Comment by wlsf82** [comment]
After the the release is created, it will not break the solution proposed by my Medium post, right?

**Comment by skwakman** [comment]
@wlsf82 The solution from your post should still work (the propertiesFn function still gets the same capabilities object). However the problem won't exist anymore :)

**Comment by rajiv503in** [comment]
please get me out of this i have left Xebia long time back

**Comment by hierynomus** [comment]
@rajiv503in Just unwatch the repository in the Github UI

**Comment by wlsf82** [comment]
Oh, nice @skwakman, thanks!

**Comment by skwakman** [comment]
`visualreview-protractor` 0.3.0 has just been released, which includes this fix. Closing bug, thanks all!
